apiVersion: v1
kind: Service
metadata:
  name: duckdb-worker
  labels:
    app: duckdb-worker
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: duckdb-worker
  #duckdb-worker.default.svc.cluster.local:8002
  #duckdb-worker:8002