apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgresql
type: Opaque
data:
  POSTGRES_USER: ZGVsdGE=
  POSTGRES_PASSWORD: ZGVsdGFwYXNz
  POSTGRES_DB: ZGVsdGFyb3V0ZXI=