apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-schema-init
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: schema-init
        image: postgres:16
        imagePullPolicy: IfNotPresent
        command:
        - psql
        - -h
        - postgresql
        - -U
        - $(POSTGRES_USER)
        - -d
        - $(POSTGRES_DB)
        - -f
        - /schema/schema.sql
        envFrom:
        - secretRef:
            name: postgresql-secret
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: schema # Refers to the volume defined below
          mountPath: /schema # This is where it will be available inside the container
      volumes:
      - name: schema # Define a volume that will hold the schema.sql file
        configMap:
          name: postgresql-schema # <- Fill this volume with the content of the ConfigMap
#kubectl create configmap postgresql-schema --from-file=schema.sql=routing-service/db/schema.sql --dry-run=client -o yaml | kubectl apply -f -
#kubectl apply -f k8s/postgresql-schema-job.yaml