apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "delta-router.routingService.fullname" . }}-model-storage
  labels:
    {{- include "delta-router.labels" . | nindent 4 }}
    app: routing-service
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.routingService.modelStorage.storageClass }}
  storageClassName: {{ .Values.routingService.modelStorage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.routingService.modelStorage.size }}
