apiVersion: v1
kind: Service
metadata:
  name: routing-service
  labels:
    {{- include "delta-router.labels" . | nindent 4 }}
    app: routing-service
spec:
  type: {{ .Values.routingService.service.type }}
  ports:
  - port: {{ .Values.routingService.port }}
    targetPort: {{ .Values.routingService.port }}
    protocol: TCP
    name: http
  selector:
    app: routing-service