{{- if .Values.secrets.adminCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "delta-router.fullname" . }}-admin-credentials
  labels:
    {{- include "delta-router.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.secrets.adminCredentials.username }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminCredentials.password }}
{{- end }}