apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "delta-router.webUi.fullname" . }}-config
  labels:
    {{- include "delta-router.labels" . | nindent 4 }}
    app: web-ui
data:
  ROUTING_SERVICE_URL: "http://routing-service:{{ .Values.routingService.port }}"