apiVersion: v1
kind: Service
metadata:
  name: web-ui
  labels:
    {{- include "delta-router.labels" . | nindent 4 }}
    app: web-ui
spec:
  type: {{ .Values.webUi.service.type }}
  ports:
  - port: {{ .Values.webUi.port }}
    targetPort: {{ .Values.webUi.port }}
    protocol: TCP
    name: http
  selector:
    app: web-ui